### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by takotakot** [phys-ken/saitenGiri2021#2]
こんにちは。

`Readme.md` には

> 無断で改造、商用利用は認めていません。

とありますが、`LICENSE` は、GPLv3 で準備されています。

`Readme.md` においての条項が優先で、非商用利用者に対して GPLv3 を課すライセンスでしょうか（デュアルというか、条件付きライセンス）。そうだとしますと、非商用で fork した人が公開すると、さらにその fork は商用可になるように思います。

それとも、`Readme.md` を修正予定でしょうか。

特に、非日本語話者が見たときに紛らわしくない形式が良いと思います。

参考:

> <program>  Copyright (C) <year>  <name of author>

は埋めておいたほうが良いかと思います。

**Comment by phys-ken** [comment]
たしかに、矛盾がありますね、readmeを修正予定です。
ライセンスは調べながらなんとなくでやってるので、もう少ししっかり調べます…！

私は…
・改造はご自由に
・でも「ここを参考にした」とは書いてほしいな
・あとは、コードを公開したフリーソフトのままにして欲しいな。
・商用とかはやる人いないと思うけど…やるんなら一応事前に一声かけてね
と思っています、よろしくお願いします。

**Comment by takotakot** [comment]
ありがとうございます。

「お気持ち」は分かるのですが、

> ・商用とかはやる人いないと思うけど…やるんなら一応事前に一声かけてね

これは、GPLv3 のみでは達成できないと思います。「声かけてほしいなぁ」と「声をかけなければいけない」には、ライセンス上大きな違いがあります。

`Readme.md` を修正予定とのこと、意向が分かりましたので、Close いたします。

**Comment by phys-ken** [comment]
確かにおっしゃる通りですね、そうした視点で物事を考えていなかったので、参考になります。アドバイスありがとうございました。(文面がなんだか皮肉っぽくなっちゃいますけど、初めてのソフト公開で右も左もなので、本当に参考になっています。)
GPL 3であれば、商用利用でもソースコードの公開が必要なはずなので、そこさえ守って頂ければいいと思ってます。
今後ともよろしくお願いします。
